### ISSUE TITLE
Background Vermelho

### ISSUE THREAD

**Issue by TabajaraKrausburg** [jomifred/latex#1]
Oi,

O background vermelhor em alguns caracteres é normal? acontence com o `^` tbm

Segue um exemplo:
[latex.pdf](https://github.com/jomifred/latex/files/2496670/latex.pdf)

**Comment by jomifred** [comment]
nao é normal. o exemplo que tem em
	https://github.com/jomifred/latex/blob/master/test/main.pdf

esse efeito nao aparece. talvez falte alguma definicao no .tex, veja
	https://github.com/jomifred/latex/blob/master/test/main.tex


> On 19 Oct 2018, at 13:52, TabajaraKrausburg <notifications@github.com> wrote:
> 
> Oi,
> 
> O background vermelhor em alguns caracteres é normal? acontence com o ^ tbm
> 
> Segue um exemplo:
> latex.pdf
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
Jomi Fred Hubner
Department of Automation and Systems Engineering
Federal University of Santa Catarina
PO Box 476, Florianópolis, SC
88040-900 Brazil
http://jomi.das.ufsc.br
-- 
be good. be kind. be happy. (Conrad Anker)

**Comment by TabajaraKrausburg** [comment]
É verdade, o exemplo que enviei estava com a definição errada, ele utilizava a definição do agente jason para o jcm.

Mas ainda não descobri pq o `^` não é reconhecido nos meta-eventos.

**Comment by jomifred** [comment]
creio q arrumei o ^

Tem que atualizar a imagem do docker
	docker pull jomifred/late

**Comment by TabajaraKrausburg** [comment]
Perfeito @jomifred está funcionando, obrigado!

> creio q arrumei o ^ Tem que atualizar a imagem do docker docker pull jomifred/late
> […](#)
> On 19 Oct 2018, at 17:39, TabajaraKrausburg ***@***.***> wrote: É verdade, o exemplo que enviei estava com a definição errada, ele utilizava a definição do agente jason para o jcm. Mas ainda não descobri pq o ^ não é reconhecido nos meta-eventos. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
